# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/planner.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/planner.proto", :syntax => :proto3) do
    add_message "planner.NewPokerRequest" do
      optional :team_name, :string, 1
      optional :team_size, :string, 2
    end
    add_message "planner.NewPokerResponse" do
      optional :error, :string, 1
    end
  end
end

module Planner
  NewPokerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("planner.NewPokerRequest").msgclass
  NewPokerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("planner.NewPokerResponse").msgclass
end
