# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/planner.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/planner.proto", :syntax => :proto3) do
    add_message "planner.NewPokerRequest" do
      optional :team_size, :int32, 1
    end
    add_message "planner.NewPokerResponse" do
      optional :poker_id, :string, 1
      optional :error, :string, 2
    end
    add_message "planner.GetPokerRequest" do
      optional :poker_id, :string, 1
    end
    add_message "planner.Vote" do
      optional :name, :string, 1
      optional :note, :int32, 2
    end
    add_message "planner.GetPokerResponse" do
      optional :team_size, :int32, 1
      repeated :votes, :message, 2, "planner.Vote"
      optional :error, :string, 3
    end
    add_message "planner.VotePokerRequest" do
      optional :poker_id, :string, 1
      optional :vote, :message, 2, "planner.Vote"
    end
  end
end

module Planner
  NewPokerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("planner.NewPokerRequest").msgclass
  NewPokerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("planner.NewPokerResponse").msgclass
  GetPokerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("planner.GetPokerRequest").msgclass
  Vote = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("planner.Vote").msgclass
  GetPokerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("planner.GetPokerResponse").msgclass
  VotePokerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("planner.VotePokerRequest").msgclass
end
